### PR TITLE
Update Ui for PersonCard to display an Image according to Status

### PR DESCRIPTION
**Pull request by bakano98**
When a person has a particular status, it will show their corresponding image.

If a person has no status, then a placeholder (fully transparent) is used instead.

I also edited the JavaFX version for `AddWindow` to the correct version (JavaFX 11)

edit: removed `Status` `Label`, now the 3 different types of statuses look like this, in order:
1) blacklisted individuals
2) favourited individuals
3) individuals with no `Status`
image

### CODE REVIEW

**Review by lawwm — COMMENTED** [review]
LGTM

**Review by Btaykb — COMMENTED** [review]
Maybe can consider removing the `blacklist` and `favourite` text from the UI since users can just refer to the images to identify the status, but otherwise LGTM

**Comment by bakano98** [comment]
> Maybe can consider removing the `blacklist` and `favourite` text from the UI since users can just refer to the images to identify the status, but otherwise LGTM

Good point, removed the `Label` in the latest commit

**Comment by bakano98** [comment]
Merging this PR as all suggestions have been taken into account and updated accordingly

**Pull request merged**
