### PR TITLE
Final changes branch

### PR DESCRIPTION
**Pull request by lawwm**
1. Fixed bug where you can add modules in `AddCommand` (Non-GUI version).
2. Fixed bug where list does not show all persons when undoing a switch command.
3. Fix UG bug where command summary format does not correspond to features.

### CODE REVIEW

**Review by bakano98 — COMMENTED** [review]
LGTM

**Comment by junlee1991** [comment]
LGTM

**Review by fantablack — COMMENTED** [review]
image

The removal of Module Parsing results in the prefix + module entered by the user being appended to the address field. Should we leave the Module Parsing in to parse and ignore modules instead? @lawwm 

I suspect a tester might flag this as a bug.

**Comment by fantablack** [comment]
> image
> 
> The removal of Module Parsing results in the prefix + module entered by the user being appended to the address field. Should we leave the Module Parsing in to parse and ignore modules instead? @lawwm

I suspect a tester might flag this as a bug

**Review by Btaykb — COMMENTED** [review]
Other than the issue raised up about the removal of Module Parsing, LGTM. Able to merge once the issue is resolved

**Comment by lawwm** [comment]
> image
> 
> The removal of Module Parsing results in the prefix + module entered by the user being appended to the address field. Should we leave the Module Parsing in to parse and ignore modules instead? @lawwm
> 
> I suspect a tester might flag this as a bug.

I think this happens generally for fields that do not have strict checks like address and comments. 
`comment 2 c/fake comment m/cs2103t` will have this issue as well.
Imo, don't need check cos you can cause that issue for any prefix, both existent and non-existent? `f/` `tg/` `r/` 
Maybe can mention in user guide, but not sure how to phrase it?

**Comment by fantablack** [comment]
> I think this happens generally for fields that do not have strict checks like address and comments. `comment 2 c/fake comment m/cs2103t` will have this issue as well. Imo, don't need check cos you can cause that issue for any prefix, both existent and non-existent? `f/` `tg/` `r/` Maybe can mention in user guide, but not sure how to phrase it?

Yup it does, and at this point its definitely better to address this in the user guide instead. Perhaps for add (CLI) we can say something like "prefixes for optional fields would be read as part of...". But then again this opens a can of worms as it overcomplicates the write-up in the UG and technically our UG explicitly says what prefixes are part of the format already.

Do you want to just leave it as is? @lawwm

**Comment by bakano98** [comment]
I think it's okay as it is. Perhaps if it gets flagged as a bug, we can argue about it.

**Pull request merged**
