### PR TITLE
Update DG

### PR DESCRIPTION
**Pull request by junlee1991**

### CODE REVIEW

**Review by lawwm — COMMENTED** [review]
You are supposed to use the `PlantUML` files to create diagrams in `tp/docs/diagrams`.
You can find more details in [week 10 project.](https://nus-cs2103-ay2122s2.github.io/website/schedule/week10/project.html)
Here is a guide for [PlantUML.](https://se-education.org/guides/tutorials/plantUml.html)

**Review by bakano98 — COMMENTED** [review]
The diagrams are fine, but do use `PlantUML` for diagramming and commit the `.puml` files for consistency across this project.

**Comment by junlee1991** [comment]
I've made the changes.

**Comment by bakano98** [comment]
> I've made the changes.

Images 2 - 5, and 7 do not follow the standards in this module. Not supposed to have the `C` beside class name. Review [Week 8's materials](https://nus-cs2103-ay2122s2.github.io/website/schedule/week8/topics.html#W8-1)

**Comment by bakano98** [comment]
Sorry, image 0 also, missed that one out. After that change has been made, I think we can merge this.

**Comment by junlee1991** [comment]
image 0 updated

**Comment by bakano98** [comment]
> image 0 updated

There's a typo, should not be `CommandResults` but rather `CommandResult`.

Also, I just noticed that it's still not following the convention. Here's an (not so concrete) example:
image

Note the following:
- Visibility is denoted by `+`, `-`. Protected (I think it's `#`) is something else, you can find from the textbook.
- Return type (or type) is after class/variable name, separated by a colon `:`
- Method signature does not need to show parameters name I think, should be optional. But if following the example, it should be something like `exampleFunction(varName1: TYPE, varName2: TYPE): RETURN_TYPE`

**Review by fantablack — COMMENTED** [review]
Class diagrams appear to be missing accessibility symbols.

Also, I suggest removing the empty rows under the classes if you do not plan to put any methods and variables there

**Pull request closed without merging**
