### PR TITLE
Fix archive undo branch

### LINKED ISSUE #131: List should not be unfiltered and unfound after adding modules/status/comment
1. Filter/Find a contact.
2. Add a module.
3. Automatically list all contacts again.

### LINKED ISSUE #143: [PE-D] Suggestion for user Guide for sorting
Could use a better word than "larger", the instruction might be clear to developers but not every users might understand. 

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: blaketingyu/ped#4

### LINKED ISSUE #150: [PE-D] Functionality of undo feature does not follow expectation
**What the bug is about?**
It is stated in the UG that the undo feature does not include switch, archive or unarchive.

However, after executing an add command in the default window, then switching to the archive, I am able to successfully enter the command `undo` (i.e. the feedback box states undo was successful). Yet, this does not bring me back to the default window, whereby switch should have been the last command executed if undo was successful.

Further, even though the undo was `successful` the last add command before the switch was also not removed when I manually switch back to the default window.

**Steps to replicate**
1. add user named `wef`
2. switch to archive
3. enter undo command
4. switch back to default - `wef` user still there

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: charmainehly/ped#6

### LINKED ISSUE #174: [PE-D] Redo does not undoes Undo
Expected: undo undoes redo
Actual: Undo does not undo redo

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: blaketingyu/ped#11

### LINKED ISSUE #190: [PE-D] Validity check for modules that can be added does not match UG documentation
**What the bug is about** <br>
The UG FAQ states that all modules that can be found in NUS mod will be available on `ModuleMateFinder`, however, the following module ASP1201EN cannot be added as it does not pass the validity checks. Perhaps the documentation could be updated to simply reduce the scope of modules that can be added, as the module that fails the validity check does not seem to be for undergraduates.

**Steps to replicate the bug** <br>
1. type in `addmodule 1 m/ASP1201EN`
2. feedback shows error message

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: charmainehly/ped#14

### LINKED ISSUE #191: [PE-D] Bug in `undo` not undoing properly after executing `find` and then `edit`
**What the bug is about**<br>
It is stated in the UG that the `undo` command should work for the `find` command. However, upon executing a sequence of `find` and then `edit`, attempting to undo the edit command does not bring me back to the `find` command result screen.

**How to replicate the bug**<br>
1. type `find alex` - will display a list with only alex
2. type `edit 1 n/tom`
3. `undo` - will undo the name change from tom back to alex
4. `undo` - does not bring me back to the display with only alex found

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: charmainehly/ped#15

### PR DESCRIPTION
**Pull request by lawwm**
1. Refactor `archive` command. Shifted logic in `MainWindow` and `LogicManager` to within `ArchiveCommand` since it didn't need to alter GUI. This also automatically allow Undo/Redo to work for archive.

3. Remove addressbook and archivebook instance in `LogicManager`.  Should have been encapsulated within `Model`.

5. Saved both addressbook and archivebook state in `RedoableCommand`, which fixed issues with Undo/Redo not working with archive. 
Closes #150 #165 #195 

7. Switch should be redoable or it would feel buggy to undo/redo changes in addressbook while in archivebook and vice versa. It also changes state in model, so it should be redoable as it would be buggy. Updated UG.

9. Find and filter should not be redoable, as redo/undo should only be for state changes in addressbook (unless want to save predicate for each command as well). 
Closes #191 

11. Changed regex for module. 
Closes #190 

13. Altered user guide for sort and copy. 
Closes #143 #163 
15. Fixed the bug where the application automatically showed all persons after apply commands: 
- `AddModuleCommand`
- `ClearModulesCommand`
- `CommentCommand`
- `DeleteModuleCommand`
- `EditCommand`
- `StatusCommand`
Closes #131 

9. Redo not working with deletemodule was fixed. 
Closes #174 

10. Updated DG for archive. 

11. Fix bug in sort where it considered uppercase and lowercase instead of just sorting by alphabets.

### CODE REVIEW

**Comment by bakano98** [comment]
LGTM. I added text wrapping for `errorLabel` in both `EditWindow` and `AddWindow`

**Comment by lawwm** [comment]
> LGTM. I added text wrapping for `errorLabel` in both `EditWindow` and `AddWindow`
> 
> Also, possible to remove `undo` and `redo` from `switch`? Feels a bit trippy, plus `switch` is intuitively a UI thing, so I think it would make sense to not be able to undo a `switch` command
> 
> @fantablack @Btaykb @junlee1991 would like to hear your inputs on this as well.

I think switch should be able to use `undo` and `redo`.

From UI/UX perspective, without `undo` and `redo`, you would be able to undo changes off-screen, for e.g. undo adding modules in default addressbook while you are viewing archive addressbook. Allowing switch to `undo` forces user to have to be on the addressbook that they are undoing.

What is more important however is the implementation perspective. Currently, UI is observing one specific addressbook, and we switch by swapping addressbook data between that observed addressbook. Therefore, we need to let switch be `RedoableCommand` in this implementation, or you would be able to `undo`/`redo` commands in unintended addressbook.

**Review by fantablack — COMMENTED** [review]
Well done! I performed manual testing, and the bug fixes appear to be working with no obvious issues. I especially liked the decoupling of archiving logic from Logic and UI. Also great work on moving references to addressbooks away from Logic into Model, as I personally struggled to do so while still allowing the addressbooks to be accessed and modified. Thank you!

LGTM

**Comment by bakano98** [comment]
> To change, we would have to be able to swap the observation of the UI between `AddressBook` and `ArchiveBook`, instead of swapping the data in and out of the addressbook that is observed. And would have to handle data methods for both addressbook and archivebook, instead of just for the addressbook that is currently observed. Quite a bit to change just for switch to not be a `RedoableCommand`.

Hm, indeed does sound like a very cumbersome thing to do. Ignore my comment regarding `switch`, we can go with the current!

**Comment by fantablack** [comment]
> LGTM. I added text wrapping for `errorLabel` in both `EditWindow` and `AddWindow`
> 
> Also, possible to remove `undo` and `redo` from `switch`? Feels a bit trippy, plus `switch` is intuitively a UI thing, so I think it would make sense to not be able to undo a `switch` command
> 
> @fantablack @Btaykb @junlee1991 would like to hear your inputs on this as well.

@bakano98 's example makes sense when viewing `switch` purely as the only command executed and I was all for it, but when viewed as a bigger picture whereby `switch` is executed after commands such as `add`, then @lawwm perfectly explains the UX problem that can occur, changing my opinion immediately. Interesting case of how not-immediately obvious use cases can totally change the perceived implementation of a feature.

Finally, I am in support of the way UI observes only 1 addressbook instead of explicitly choosing and referencing both addressbooks, which is another reason why I vote on leaving `switch` capable of `undo redo`. :thumbsup:

**Comment by junlee1991** [comment]
I am in favor of the UI monitoring a single addressbook rather than split referencing 2 addressbooks. Hence, switch should be redoable / undoable.

**Comment by Btaykb** [comment]
> What is more important however is the implementation perspective. Currently, UI is observing one specific addressbook, and we switch by swapping addressbook data between that observed addressbook. Therefore, we need to let switch be `RedoableCommand` in this implementation, or you would be able to `undo`/`redo` commands in unintended addressbook.

I am in agreement with what @lawwm mentions here, definitely will lead to quite a bit of unwanted behaviors if we don't allow `switch` to `undo/redo`. 

Also LGTM with regards to the PR.

**Pull request merged**
