### PR TITLE
Update UI

### LINKED ISSUE #110: Differently sized buttons between EditWindow and AddWindow
image
Will standardise the sizes.

### PR DESCRIPTION
**Pull request by bakano98**
Repositioned `Comment` and `Status`
image

Not too sure about this colour scheme, looks a little weird... but I can change it back if anything.
image

Fixed inconsistent button sizes.

Do note that this is conflicting with @lawwm implementation at #103, so we need to make a decision as to whether we want the caching of comments

@fantablack @lawwm @junlee1991 @Btaykb 
~Do give feedback regarding the above.~

Updated colours:
image

We'll be using the updated layout and removing the cache function. Thanks for the feedback.

Closes #110

### CODE REVIEW

**Comment by junlee1991** [comment]
I think the caching comments makes  it easy for it to be overlooked by users.

**Comment by Btaykb** [comment]
I feel that the blue color scheme for the AddWindow/EditWindow can be a little too clashing when the base color of the main page is still black/grey. We can probably look into changing the color scheme of the main page to make it more complementary to blue.

**Comment by bakano98** [comment]
> I feel that the blue color scheme for the AddWindow/EditWindow can be a little too clashing when the base color of the main page is still black/grey. We can probably look into changing the color scheme of the main page to make it more complementary to blue.

Good point. I am actually looking into those and I do intend to change the colour scheme for the main page!

**Comment by Btaykb** [comment]
> Do note that this is conflicting with @lawwm implementation at #103, so we need to make a decision as to whether we want the caching of comments

For this matter, I understand @lawwm point of view that in the case of adding multiple similar comments, having a cache would allow for greater speed and convenience than manually typing out the same comment repeatedly. But I feel that this case may not be common enough to warrant another table for comments specifically. 

Also users might be confused with the separate table and while they could just simply read up the UG to understand its purpose and value, I feel when faced with the decision of choosing between a design than can be more easily understood at first glance vs having to search it up in the UG, we should perhaps be looking into the former.

**Review by lawwm — COMMENTED** [review]
LGTM. Btw, I've closed the cache PR.

**Comment by bakano98** [comment]
Will merge and close tomorrow if no other issues.

**Comment by bakano98** [comment]
Will merge and close tomorrow if no other issues.

**Review by Btaykb — COMMENTED** [review]
LGTM

**Comment by junlee1991** [comment]
LGTM

**Pull request merged**
