### PR TITLE
Update DG

### PR DESCRIPTION
**Pull request by fantablack**
* Add Sequence Diagram for add module
* Update ModelClassDiagram and BetterModelClassDiagram
* Fixed typo in StatusCommand.java
* Fixed typo in AddModule in DG
* Update Add/Delete Module header in UG to better reflect multiple modules processing capability

### CODE REVIEW

**Comment by fantablack** [comment]
I'll leave the Add Modules Sequence Diagram in as part of the changes first. Will consult teaching team if similar diagrams should be left in/taken out.

**Comment by lawwm** [comment]
https://github.com/nus-cs2103-AY2122S2/forum/issues/237

**Comment by fantablack** [comment]
> [nus-cs2103-AY2122S2/forum#237](https://github.com/nus-cs2103-AY2122S2/forum/issues/237) this might be the reason?

yup, in this instance its showing errors trying to resolve shadowJar

**Review by lawwm — COMMENTED** [review]
LGTM. The GitHub checks should work now. Maybe you should add Comment and Status to BetterModelClassDiagram.png

**Review by bakano98 — COMMENTED** [review]
Add `Comment` and `Status` to `Person` in BetterModelClassDiagram.png, then should be ok.

**Pull request merged**
