### PR TITLE
Update DG stuff

### PR DESCRIPTION
**Pull request by bakano98**
Please check the UML diagrams and let me know if there's anything missing for the relevant parts.

### CODE REVIEW

**Review by lawwm — COMMENTED** [review]
LGTM. However, doesn't static call to addWindowHelper() call constructor for instance of AddCommand?

**Comment by bakano98** [comment]
> LGTM. However, doesn't static call to addWindowHelper() call constructor for instance of AddCommand?

You are right. I'm not sure how that's (factory methods) supposed to be represented in UML though, so I am representing it as what a normal static method call would be like.

Any suggestions on how to represent it instead?

**Comment by Btaykb** [comment]
> > LGTM. However, doesn't static call to addWindowHelper() call constructor for instance of AddCommand?
> 
> You are right. I'm not sure how that's (factory methods) supposed to be represented in UML though, so I am representing it as what a normal static method call would be like.
> 
> Any suggestions on how to represent it instead?

factory-method-sequence

Found this online, maybe can apply to the addWindowHelper()

**Comment by bakano98** [comment]
Hui Ting says the current one is ok, so I will leave it as it is!

**Review by Btaykb — COMMENTED** [review]
LGTM

**Pull request merged**
